name: squad-tutorial
dependencies:
- ca-certificates=2016.2.28=0
- certifi=2016.8.2=py35_0
- cloudpickle=0.2.1=py35_0
- cymem=1.31.2=py35_0
- mkl=11.3.3=0
- murmurhash=0.26.4=py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=2
- pip=8.1.2=py35_0
- plac=0.9.1=py35_0
- preshed=0.46.4=py35_0
- protobuf=3.0.0b2=py35_0
- python=3.5.2=2
- readline=6.2=2
- semver=2.4.2=py35_0
- setuptools=25.1.3=py35_0
- simplejson=3.8.2=py35_0
- six=1.10.0=py35_0
- spacy=0.100.7=py35_0
- sputnik=0.9.3=py35_0
- sqlite=3.13.0=1
- tensorflow=0.9.0=py35_0
- thinc=5.0.8=py35_0
- tk=8.5.19=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - beautifulsoup4==4.4.1
  - decorator==4.0.10
  - entrypoints==0.2.2
  - h5py==2.6.0
  - ipykernel==4.3.1
  - ipython==5.0.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - keras==1.0.5
  - markupsafe==0.23
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.0.1
  - notebook==4.2.1
  - pexpect==4.2.0
  - pickleshare==0.7.3
  - prompt-toolkit==1.0.3
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyyaml==3.11
  - pyzmq==15.3.0
  - qtconsole==4.2.1
  - regex==2016.6.24
  - requests==2.10.0
  - scipy==0.17.1
  - simplegeneric==0.8.1
  - terminado==0.6
  - theano==0.9.0.dev1
  - tornado==4.4.1
  - tqdm==4.8.2
  - traitlets==4.2.2
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6

